class ActionTypes{
   static GET_USERS_REQUEST='GET_USERS_REQUEST';
   static GET_USERS_SUCCESS='GET_USERS_SUCCESS';
   static CREATE_USER_REQUEST='CREATE_USER_REQUEST';
   static DELETE_USER_REQUEST='DELETE_USER_REQUEST';
   static USER_ERROR='USER_ERROR';
}
export {ActionTypes}
